config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  get 'profiles/edit'
  get 'profiles/update'
  devise_for :users
  
  root to: "pages#home_befor_login"

  get "/home_after_login" ,to: "pages#home_after_login", as: :home_after_login

  # resources :question_and_answers, only: [:index ]
  resources :question_and_answers do
    resources :reviews, only: [:create]
  end
  resources :coffee_machines
  resources :error_messages, only: [:show]
  resources :user_coffee_machines, only: [:create]

  resource :profile, only: [:show, :edit, :update]

  get 'my_coffeemachine', to: 'coffee_machines#my_coffeemachine'

  # Route to handle the form submission
  post 'contact_manufacture', to: 'support#create', as: :manufacture_contact
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/question_and_answer.rb
class QuestionAndAnswer < ApplicationRecord
  has_many :reviews
  belongs_to :coffee_machine_model
end

app/controllers/question_and_answers_controller.rb
class QuestionAndAnswersController < ApplicationController

  def show
    @question_and_answer = QuestionAndAnswer.find(params[:id])
    @reviews = Review.where(question_and_answer_id: @question_and_answer.id)
  end

    def index
      @questions = QuestionAndAnswer.all
      @search_word = params[:query]
      if params[:query].present?
        sql_subquery = "question ILIKE :query OR answer ILIKE :query"
        @questions = @questions.where(sql_subquery, query: "%#{params[:query]}%")
      end
    end

    def create_review
      @question_and_answer = QuestionAndAnswer.find(params[:id])
      @review = @question_and_answer.reviews.new(review_params)
      @review.user = current_user # Assuming you have user authentication
      if @review.save
        redirect_to question_and_answer_path(@question_and_answer), notice: 'Review added successfully.'
      else
        redirect_to question_and_answer_path(@question_and_answer), alert: 'Failed to add review.'
      end
    end

    private

    def review_params
      params.require(:review).permit(:content)
    end
end

app/views/question_and_answers/index.html.erb
<div class="container-lg ">
<div class="QandA-container">
  <div class="QandA-title">
    <h2 style="text-align:center;">Common Questions Answered: Find Solutions Here</h1>
  </div>
  <div class="row justify-content-center ">
    <div class="col-lg-4 col-md-6 col-10 mt-3 mt-md-5 ">
      <%= form_with url: question_and_answers_path, method: :get, class: "d-flex search-box-QandA " do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              style: "border:none;",
              placeholder: "Type a keyword"
          %>
        <%= submit_tag "Search", name: "", class: "btn search-QandA-button m-1 rounded-4" %>
      <% end %>
    </div>
  </div>

  <div class="flex-container ">
    <% if @questions.empty? %>
      <div class="nothing-found-search-QandA mt-4">
        <p > nothing found with <b>"<%= params[:query] %>"</b></p>
      </div>
    <% else %>
      <div>
        <% @questions.each do |question| %>
          <%= render "shared/revews_modal", question: question %>


            <div class="row question-answer-QandA mt-md-2 mt-5 mx-1">
              <%# <div class="col-md-1 col-0"></div> %>
              <div class="col-md-5 col-12 question-QandA">

                <h3><%= highlight(question.question, params[:query],highlighter: '<em class="highlighter">\1</em>') %></h3>

              </div>
              <div class="px-5 d-block d-md-none">
                  <hr />
              </div>

              <div class=" col-md-2  line-container-QandA d-none d-md-block">
                <div class="qa-line-QandA"></div>
                <i class="fa-solid fa-hammer icon-qa-QandA"></i>
              </div>
                <div class="d-md-none d-block">
                <i class="fa-solid fa-hammer icon-qa-QandA"></i>
              </div>
              <div class="col-md-5 col-12 answer-QandA">

              <p><%= highlight(question.answer, params[:query],highlighter: '<em  class="highlighter">\1</em>') %></p>

                <div class=" reply-icon-QandA text-center">
                  <i class="fa-solid fa-reply" data-bs-toggle="modal" data-bs-target="#reviewModal<%= question.id %>"></i>
                  <span class="reply-count-QandA"><%= question.reviews.count %></span>
                </div>
              </div>
          </div>

        <% end %>
    </div>

    <% end %>
  </div>



</div>