config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  get 'profiles/edit'
  get 'profiles/update'
  devise_for :users
  
  root to: "pages#home_befor_login"

  get "/home_after_login" ,to: "pages#home_after_login", as: :home_after_login

  # resources :question_and_answers, only: [:index ]
  resources :question_and_answers do
    resources :reviews, only: [:create]
  end
  resources :coffee_machines
  resources :error_messages, only: [:show]
  resources :user_coffee_machines, only: [:create]

  resource :profile, only: [:show, :edit, :update]

  get 'my_coffeemachine', to: 'coffee_machines#my_coffeemachine'

  # Route to handle the form submission
  post 'contact_manufacture', to: 'support#create', as: :manufacture_contact
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coffee_machine.rb
class CoffeeMachine < ApplicationRecord
  belongs_to :coffee_machine_model
  has_one_attached :photo
  has_many :user_coffee_machines
  validates :machine_type, presence: true
end

app/models/coffee_machine_model.rb
class CoffeeMachineModel < ApplicationRecord
  has_many :error_messages
  has_many :question_and_answers
  has_many :coffee_machines
end

app/models/error.rb
class Error < ApplicationRecord
  belongs_to :coffee_machine_model
end

app/models/error_message.rb
class ErrorMessage < ApplicationRecord
  belongs_to :coffee_machine_model
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_many :user_coffee_machines
end

app/models/question_and_answer.rb
class QuestionAndAnswer < ApplicationRecord
  has_many :reviews
  belongs_to :coffee_machine_model
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :question_and_answer
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :user_coffee_machines
  has_many :reviews
end

app/models/user_coffee_machine.rb
class UserCoffeeMachine < ApplicationRecord
  belongs_to :user
  belongs_to :manager
  belongs_to :coffee_machine
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  def after_sign_in_path_for(*)
    home_after_login_path # your path
  end
end

app/controllers/coffee_machines_controller.rb
class CoffeeMachinesController < ApplicationController
  def index
    @coffee_machines = CoffeeMachine.all
    @allerrors = ErrorMessage.all
  end

  def show
    @coffee_machine = CoffeeMachine.find(params[:id])
  end

  def my_coffeemachine
    @user_coffeemachines = UserCoffeeMachine.where(user_id: current_user.id).map { |user_coffee_machine| user_coffee_machine.coffee_machine }
    @user = current_user
    @coffee_machine = UserCoffeeMachine.new
  end



  def create
    @coffee_machine = current_user.coffee_machines.build(coffee_machine_params)
    if @coffee_machine.save
      redirect_to coffee_machine_path(@coffee_machine), notice: 'Coffee machine was successfully created.'
    else
      render :new
    end
  end

  private

  def coffee_machine_params
    params.require(:coffee_machine).permit(:serial_number, :coffee_machine_model_id, :manager_id)
  end

end

app/controllers/error_messages_controller.rb
class ErrorMessagesController < ApplicationController
  def show
    @error = ErrorMessage.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home_befor_login]

  def home
  end

  def home_before_login
    redirect_to root_path, notice: "You are already signed in." if user_signed_in?
  end

  def home_after_login
    # Code for the home page after login
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def my_machines
    @user = current_user
    @coffee_machines = @user.coffee_machines
  end

  def update
    @user = current_user
    if @user.update(profile_params)
      redirect_to profile_path, notice: "Profile updated successfully."
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:first_name, :last_name, :email, :address, :phone_number)
  end
end

app/controllers/question_and_answers_controller.rb
class QuestionAndAnswersController < ApplicationController

  def show
    @question_and_answer = QuestionAndAnswer.find(params[:id])
    @reviews = Review.where(question_and_answer_id: @question_and_answer.id)
  end

    def index
      @questions = QuestionAndAnswer.all
      @search_word = params[:query]
      if params[:query].present?
        sql_subquery = "question ILIKE :query OR answer ILIKE :query"
        @questions = @questions.where(sql_subquery, query: "%#{params[:query]}%")
      end
    end

    def create_review
      @question_and_answer = QuestionAndAnswer.find(params[:id])
      @review = @question_and_answer.reviews.new(review_params)
      @review.user = current_user # Assuming you have user authentication
      if @review.save
        redirect_to question_and_answer_path(@question_and_answer), notice: 'Review added successfully.'
      else
        redirect_to question_and_answer_path(@question_and_answer), alert: 'Failed to add review.'
      end
    end

    private

    def review_params
      params.require(:review).permit(:content)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create

    @question_and_answer = QuestionAndAnswer.find(params[:question_and_answer_id])
    @review = @question_and_answer.reviews.new(review_params)
    @review.user = current_user
    if @review.save!
      redirect_to question_and_answers_path, notice: 'Review was successfully created.'
    else
      render 'question_and_answers/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController

  def create
    redirect_to home_after_login_path, notice: 'We will contact you as soon as possible!'
    # Logic to handle form submission
    # For example, send an email or save the contact inquiry
  end

  def contact_manufacture
    # Your logic to handle the contact form submission goes here
  end
end

app/controllers/user_coffee_machines_controller.rb
class UserCoffeeMachinesController < ApplicationController
  def create
    @coffee_machine = current_user.user_coffee_machines.build(coffee_machine_params)
    if @coffee_machine.save
      redirect_to my_coffeemachine_path, notice: 'Coffee machine was successfully added.'
    else
      render :new
    end
  end

  private

  def coffee_machine_params
    params.require(:user_coffee_machine).permit(:serial_number, :coffee_machine_id, :manager_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrewTechMechanic</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>
  <body>
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/home_after_login.html.erb
<div class="hompage-container">
  <div class="homepage-topimage-container">
    <%= image_tag "homepage_girl.png", alt:"Homepage Image", class:"homepage-image-top" %>
    <div data-controller="slideshow" class="homepage-slideshow ">
      <div class="slideshow-container">
        <% 7.times do |i| %>
          <div class="line-and-dot-container">
            <div class="dot-container">
              <span class="number-in-dot"><%= i+1 %></span>
              <span class="dot" data-action="click->slideshow#currentSlide" data-slideshow-target="dot" data-slide-index="<%= i %>" ></span>
            </div>

            <% if i < 6 %>
              <div class="line-slideshow"> </div>
            <% end %>
          </div>
        <% end %>

        <% text =["Brewing Solutions, Anywhere, Anytime", "Espresso expertise at your service",
                  "Your coffee companion, supporting every sip",
                  "From bean to machine: support that understands", "Wake up to world-class coffee machine service",
                  "Because we care, your coffee never stops", "Global support, local care for your coffee machine"] %>
        <% 7.times do |i| %>
          <div class="mySlides fade " data-slideshow-target="slide" data-index="<%= i %>">
            <p class="text-slideshow"><%= "#{text[i]}" %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <%# <div class=""> %>
    <div class="content gray-space row ">
      <div class="text-container col-12 col-lg-5 ">
        <div class="text-homepage-gray-space">Having trouble with your Coffee Machine?
          <div style="text-align:center;" class="my-3"><b>We want to help!</b></div>
          You can read instructions or watch video
        </div>
      </div>
      <div class="col-lg-2 d-none d-lg-block"></div>
      <div class="button-container  col-lg-5 col-12">
        <button class="btn ">
          <%= link_to "Click HERE to find more information", coffee_machines_path, class: "nav-link" %>
        </button>
      </div>
    </div>
  <%# </div> %>

  <div class="ask-question-space" style="text-align:center;"><p>Do you have a question about coffee or coffee machine?</p>
    <div class="row mt-5">
      <div class="col-xl-4 col-md-6">
        <div class="question-card">
          <%= image_tag "coffee_icon_2.png", alt: "icon Image", class: "img-fluid mt-4" %>
            <ul>
              <li class="mt-5">Can i feel long cups or thermoses in my coffee machine?</li>
              <li class="mt-2">What temperature is good for tea water?</li>
            </ul>
        </div>
      </div>

      <div class="col-xl-4 col-md-6 ">
        <div class="question-card">
          <%= image_tag "coffee_icon_1.png", alt: "icon Image", class: "img-fluid mt-4" %>
            <ul>
              <li class="mt-5">Do i need a filter for my coffee machine?</li>
              <li class="mt-2">How many grams of coffee is recommended per cup?</li>
            </ul>
        </div>
      </div>

      <div class="col-md-4  d-block d-md-none d-xl-block">
        <div class="question-card">
          <%= image_tag "coffee_icon_2.png", alt: "icon Image", class: "img-fluid mt-4" %>
            <ul>
              <li class="mt-5">What voltage is needed for the coffee machine?</li>
              <li class="mt-2">What should be the height of the bar counter for barista?</li>
            </ul>
        </div>
      </div>

    </div>

    <div class="button-container my-0 my-lg-5">
      <button class="btn">
        <%= link_to "FIND YOUR ANSWERS HERE", question_and_answers_path, class: "nav-link" %>
      </button>
    </div>
  </div>
</div>

app/views/pages/home_befor_login.html.erb
<body class="landing-page-body">
<% image_array = ["background-image-2.jpg" ,"background-image-1.jpg","background-image-3.jpg","background-image-4.jpg" ] %>
<% text_array_top = ["Worldwide support" , "Global assistance"," Everything about","We work for you, "] %>
<% text_array_bottom = ["for your coffee machine is here" ,"for your coffee machine","your coffee machine at your fingerprints","so you can just relax and brew" ] %>

  <div class="slideshow-landingpage" data-controller="slideshow">
    <% 4.times do |i| %>
        <div class="" data-slideshow-target="slide" data-index="<%= i %>">
            <%= image_tag "#{image_array[i]}", class: "slide-landingpage" %>
            <div class="support-text-landingpage mt-5 mt-sm-0 pt-sm-2 pt-5 "><b><%= text_array_top[i] %></b><br> <%= text_array_bottom[i] %></div>
        </div>
      <% end %>
      <div class="button-container-landingpage">
          <% 4.times do |i| %>
            <span class="dot-landingpage" data-action="click->slideshow#currentSlide" data-slideshow-target="dot" data-slide-index="<%= i %>"></span>
          <% end %>
        </div>
</div>



<% if user_signed_in? %>
  <%= link_to 'Log Out', destroy_user_session_path, data: {turbo_method: :delete} %>
<% else %>

<% end %>
</body>

app/views/shared/_contact_modal.html.erb
<div class="modal fade modal-review-background" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true">
  <div class="modal-dialog " role="document">
    <div class="modal-content modal-contact ">
      <div class="contact-modal-box">

        <div class="modal-header ">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
           <h5 class="modal-title my-4" id="contactModalLabel">Do you have a technical question about one of your coffee machines?
          We will be happy to help you! Please fill out the form below:</h5>
          <%= form_with(url: manufacture_contact_path, method: :post, local: true) do |form| %>
            <div class="mb-3">
              <%= form.label :preferred_language, 'Please choose language you would like to use  ' %>
              <%= form.select :preferred_language, ['English', 'Spanish', 'German', 'Russian'], {}, {class: 'form-control', required: true} %>
            </div>

            <div class="mb-3" data-controller="flatpickr">
              <%= form.label :start_time, 'Start Time:' %>
              <%= form.text_field :start_time, data: { flatpickr_target: "startTime" }, class: 'form-control', required: true %>

              <%= form.label :end_time, 'End Time:' %>
              <%= form.text_field :end_time, data: { flatpickr_target: "endTime" }, class: 'form-control', required: true %>
            </div>

            <div class="mb-3">
              <%= form.label :contact_method, 'Please choose social media for contact:' %>
              <%= form.select :contact_method, ['WhatsApp', 'Telegram', 'Phone Call'], {}, {class: 'form-control', required: true} %>
            </div>

            <div class="mb-3">
              <%= form.label :message, 'Please type your message here:' %>
              <%= form.text_field :message, class: 'form-control', rows: 9, required: true %>
            </div>

            <div class="modal-footer">
              <%= form.submit "Send", class: 'btn contact-send-button'  %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_drowpdowns.html.erb
  <div class="dropdown card-text">

  <button class="btn cofeenachine-button-blue dropdown-toggle my-2 " type="button" id="detailsDropdown" data-bs-toggle="dropdown" aria-expanded="false">
      View details
  </button>
    <ul class="dropdown-menu details-cofeemachine-drowpdown " aria-labelledby="detailsDropdown">
      <div class="p-4 coffeemachine-card-border">
        <li><b> <%= coffee_machine.machine_type %></b></li>
        <li><%= coffee_machine.description %></li>
      </div>
    </ul>

  <button class="btn cofeenachine-button-orange dropdown-toggle" type="button" id="errorDropdown" data-bs-toggle="dropdown" aria-expanded="false">
    Choose Error
  </button>
    <ul class="dropdown-menu error-cofeemachine-drowpdown" aria-labelledby="errorDropdown">
        <% @allerrors.each do |error| %>
          <% if error.coffee_machine_model_id == coffee_machine.coffee_machine_model_id %>
            <li><%= link_to error.error_code, error_message_path(error), class:"dropdown-item" %></li>
          <% end %>
        <% end %>
    </ul>

 </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_login_modal.html.erb
<div class="modal fade modal-login-background" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog ">
    <div class="row modal-size modal-size-login">
    <div class="d-md-block d-none col-md-6 left-login-modal ">
      <i class="fa-solid fa-mug-hot"></i>
      <div class="text-center left-login-modal-content">
        <div class="">
         <p>Worlwide support for your coffee machine is here</p>
        </div>
        <br/>
        <i class="fa-solid fa-screwdriver-wrench"></i>
      </div>
    </div>
    <div class="col-12 col-md-6 ">
      <div class="modal-content">
        <div class="modal-header ">
          <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <h5 class="modal-title  mb-5" id="loginModalLabel">Login to your Account</h5>

          <%= render 'devise/sessions/new'%>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% transparent_paths = ["/", "/home_after_login"] %>
<% background =  transparent_paths.include?(request.path) ? "navbar-transparent" : "navbar-background" %>
<div class="navbar-top   <%= background %>">
  <div class="navbar navbar-expand navbar-dark navbar-style">

    <%= link_to  home_after_login_path	, class: "navbar-brand style-logo" do %>
      <%= image_tag "Rectangle 13(1).png" %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav me-auto ">

        <% if user_signed_in?%>

          <input id="menu-toggle" type="checkbox" />
          <label class='menu-button-container' for="menu-toggle">
            <div class='menu-button'></div>
          </label>
          <ul class="menu-box">
            <li class="nav-item mx-2 d-lg-none ">
              <%= link_to "home", home_after_login_path, class: "nav-link nav-button-blue"%>
            </li>

            <li class="nav-item mx-2 ">
              <%= link_to 'Coffee Machines', coffee_machines_path ,class: "nav-link nav-button-blue" %>
            </li>
            <li class="nav-item mx-2">
              <%= link_to "Questions and Answers", question_and_answers_path, class: "nav-link nav-button-blue" %>
            </li>
            <li class="nav-item mx-2">
              <%= link_to "Contact Manufacture", manufacture_contact_path, class: "nav-link nav-button-blue", data: { bs_toggle: "modal", bs_target: "#contactModal" } %>
            </li>
            <li class="nav-item mx-2 ">
                <a href="#" class="avatar nav-link dropdown-toggle nav-button-orange" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-action="click->dropdown#showMenu">
                  <%= tag.i ' ', class: "fa-solid fa-user", alt: "dropdown menu" %>
                </a>
                <div class="dropdown-menu drowpdown-navbar-profile dropdown-menu-end" aria-labelledby="navbarDropdown" data-dropdown-target="menu">

                  <%= link_to "My Profile", profile_path, class: "dropdown-item" %>
                  <%= link_to "My Coffee Machines", my_coffeemachine_path, class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
              </li>



          </ul>

        <% else %>

          <li class="nav-item mx-2  ">
            <button type="button" class="btn  nav-link nav-landingpage-button-orange" data-bs-toggle="modal" data-bs-target="#loginModal">
              Login
            </button>
          </li>
          <li class="nav-item mx-2 ">
            <button type="button" class="btn nav-link nav-landingpage-button-blue" data-bs-toggle="modal" data-bs-target="#signupModal">
              Sign Up
            </button>
          </li>

        <% end %>

      </div>
    </div>
  </div>
</div>

<%= render 'shared/contact_modal' %>
<%= render "shared/login_modal" %>
<%= render "shared/signup_modal" %>

app/views/shared/_revews_modal.html.erb
<div class="modal fade modal-review-background" id="reviewModal<%= question.id%>" tabindex="-1" aria-labelledby="reviewModalLabel" aria-hidden="true">

  <div class="modal-dialog modal-size-review">
    <div class="modal-size ">


        <div class="modal-content   modal-review-container">
          <div class="modal-header ">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class=" p-sm-4  ">
            <% question.reviews.each do |review| %>
            <div class="modal-review-eachreview m-3">
              <p><b class="name-review-modal"><%= review.user.first_name ? review.user.first_name : "no name" %></b> : <%= review.content %></p>
            </div>
            <% end %>
            <div class="">
              <%= simple_form_for [question, Review.new] do |f| %>
                <div class="d-flex add-review-modal-QandA mt-5">
                  <%= f.input :content,  input_html: { class: " form-control input-review-modal" } ,label:false %>
                  <%= f.submit "Add a review" , class: "add-review-modal-button" %>
                </div>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_signup_modal.html.erb
<div class="modal fade modal-login-background" id="signupModal" tabindex="-1" aria-labelledby="signupModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="row modal-size modal-size-signup">
    <div class=" left-login-modal d-md-block d-none col-md-6">
      <i class="fa-solid fa-mug-hot"></i>
      <div class="text-center left-login-modal-content">
        <div class="">
          <p>Worlwide support for your coffee machine is here</p>
        </div>
        <br/>
        <i class="fa-solid fa-screwdriver-wrench"></i>
      </div>
    </div>
    <div class="col-12 col-md-6 ">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
          <div class="modal-body">
            <h5 class="modal-title  mb-5" id="loginModalLabel">Sign Up for an account</h5>

            <%= render 'devise/registrations/new'%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>